// Web Application/react/src/views/dashboard/auth/sign-in.js
import React from 'react'
import { Row, Col, Form, Button } from 'react-bootstrap'
import { Link, useHistory } from 'react-router-dom'
import Card from '../../../components/card'

// img
import fav from '../.././../assets/images/favicon.png'
import fb from '../.././../assets/images/brands/fb.svg'
import gm from '../.././../assets/images/brands/gm.svg'
import li from '../.././../assets/images/brands/li.svg'
import im from '../.././../assets/images/brands/im.svg'
import auth09 from '../.././../assets/images/auth/09.png'

const SignIn = () => {
   let history =useHistory()
   return (
      <>
         <section className="container-fluid bg-circle-login" id="auth-sign">
            <Row className="align-items-center">
               <Col md="12" lg="7" xl="4">
                  <Card.Body>
                     <Link to="/">
                        <img src={fav} className="img-fluid logo-img" alt="img4"/>
                     </Link>
                     <h2 className="mb-2 text-center">Sign In</h2>
                     <p className="text-center">Sign in to stay connected.</p>
                     <Form>
                        <Row>
                           <Col lg="12">
                              <Form.Group className="form-group">
                                 <Form.Label htmlFor="email">Email</Form.Label>
                                 <Form.Control type="email" className="form-control-sm" id="email" aria-describedby="email" placeholder=" "/>
                              </Form.Group>
                           </Col>
                           <Col lg="12">
                              <Form.Group className="form-group">
                                 <Form.Label htmlFor="password">Password</Form.Label>
                                 <Form.Control type="password" className="form-control-sm" id="password" aria-describedby="password" placeholder=" "/>
                              </Form.Group>
                           </Col>
                           <Col lg="12" className="d-flex justify-content-between">
                              <Form.Check className="form-check mb-3">
                                 <Form.Check.Input type="checkbox" id="customCheck1"/>
                                 <Form.Check.Label htmlFor="customCheck1">Remember Me</Form.Check.Label>
                              </Form.Check>
                              <Link to="/auth/recoverpw">Forgot Password?</Link>
                           </Col>
                        </Row>
                        <div className="d-flex justify-content-center">
                           <Button onClick={() => history.push('/')} type="submit" variant="primary">Sign In</Button>
                        </div>
                        <p className="text-center my-3">or sign in with other accounts?</p>
                        <div className="d-flex justify-content-center">
                           <ul className="list-group list-group-horizontal list-group-flush">
                              <li className="list-group-item border-0 pb-0">
                                 <Link to="#"><img src={fb} alt="fb"/></Link>
                              </li>
                              <li className="list-group-item border-0 pb-0">
                                 <Link to="#"><img src={gm} alt="gm"/></Link>
                              </li>
                              <li className="list-group-item border-0 pb-0">
                                 <Link to="#"><img src={im} alt="im"/></Link>
                              </li>
                              <li className="list-group-item border-0 pb-0">
                                 <Link to="#"><img src={li} alt="li"/></Link>
                              </li>
                           </ul>
                        </div>
                        <p className="mt-3 text-center">
                           Don’t have an account? <Link to="/auth/sign-up" className="text-underline">Click here to sign up.</Link>
                        </p>
                     </Form>
                  </Card.Body>
               </Col>
               <Col md="12" lg="5" xl="8" className="d-lg-block d-none vh-100 overflow-hidden">
                  <img src={auth09} className="img-fluid sign-in-img" alt="images"/>
               </Col>
            </Row>
         </section>    
      </>
    )
}

export default SignIn

// Web Application/vue/src/views/pages/Authentication/SignIn.vue
<template>
   <section class="container-fluid bg-circle-login" id="auth-sign">
         <div class="row align-items-center">
            <div class="col-md-12 col-lg-7 col-xl-4">
               <div class="card-body">
                  <router-link :to="{name: 'default.dashboard'}">
                     <img src="@/assets/images/favicon.png" class="img-fluid logo-img" alt="img4">
                  </router-link>
                           <h2 class="mb-2 text-center">Sign In</h2>
                           <p class="text-center">Sign in to stay connected.</p>
                           <form>
                              <div class="row">
                                 <div class="col-lg-12">
                                    <div class="form-group">
                                       <label for="email" class="form-label">Email</label>
                                       <input type="email" class="form-control form-control-sm" id="email" aria-describedby="email" placeholder=" ">
                                    </div>
                                 </div>
                                 <div class="col-lg-12">
                                    <div class="form-group">
                                       <label for="password" class="form-label">Password</label>
                                       <input type="password" class="form-control form-control-sm" id="password" aria-describedby="password" placeholder=" ">
                                    </div>
                                 </div>
                                 <div class="col-lg-12 d-flex justify-content-between">
                                    <div class="form-check mb-3">
                                       <input type="checkbox" class="form-check-input" id="customCheck1">
                                       <label class="form-check-label" for="customCheck1">Remember Me</label>
                                    </div>
                                    <router-link :to="{name: 'auth.recoverPassword'}">Forgot Password?</router-link>
                                 </div>
                              </div>
                              <div class="d-flex justify-content-center">
                                 <button type="submit" class="btn btn-primary">Sign In</button>
                              </div>
                              <p class="text-center my-3">or sign in with other accounts?</p>
                              <div class="d-flex justify-content-center">
                                 <ul class="list-group list-group-horizontal list-group-flush">
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="@/assets/images/brands/fb.svg" alt="fb"></a>
                                    </li>
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="@/assets/images/brands/gm.svg" alt="gm"></a>
                                    </li>
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="@/assets/images/brands/im.svg" alt="im"></a>
                                    </li>
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="@/assets/images/brands/li.svg" alt="li"></a>
                                    </li>
                                 </ul>
                              </div>
                              <p class="mt-3 text-center">
                                 Don’t have an account? <router-link :to="{name: 'auth.signup'}" class="text-underline">Click here to sign up.</router-link>
                              </p>
                           </form>
                        </div>
            </div>
            <div class="col-md-12 col-lg-5 col-xl-8 d-lg-block d-none vh-100 overflow-hidden">
               <img src="@/assets/images/auth/09.png" class="img-fluid sign-in-img" alt="images">
            </div>
         </div>
      </section>
</template>
<script>
export default {
  name: 'SignIn'
}
</script>
